.TH GENNGRAMS 1 "January 2026" "libenigma" "User Commands"
.SH NAME
genngrams \- Generate n-grams from a text file.
.SH SYNOPSIS
.B genngrams
n file
.SH DESCRIPTION
This script generates n-grams from a given file. The first line of output is "n charcount",
and the subsequent lines are the n-grams themselves (formatted as "count ngram").
The output can be directly used by libenigma and enigmacrack.
.SH AUTHOR
Written by Ben O'Neill <ben@oneill.sh>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2025-2026 Ben O'Neill <ben@oneill.sh>. License: MIT.
.SH SEE ALSO
.BR enigmacli (1),
.BR enigmacrack (1),
.BR indexgen (1)
