name: Demo

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Updating website.
        uses: appleboy/ssh-action@master
        with:
          host: oneill.sh
          username: www
          key: ${{ secrets.wwwssh }}
          passphrase: ${{ secrets.wwwpass }}
          port: 22
          script: |
            cd enigma
            git stash
            git pull --force origin main
            emcc -O3 -s WASM=1 -s EXPORTED_RUNTIME_METHODS='["cwrap"]' -s EXPORTED_FUNCTIONS='["_malloc", "_free", "stringToUTF8", "UTF8ToString"]' -s ALLOW_MEMORY_GROWTH=1 -I src/enigma/ src/enigma/*.c
            mv a.out.js a.out.wasm /var/www/html/apps/enigma
            mv webdemo/* /var/www/html/apps/enigma/
